---
# Python 3 with Redis
version: "3"

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    hostname: nyu
    container_name: lab-github-actions
    volumes:
      - ..:/app
    command: sleep infinity
    environment:
      FLASK_APP: wsgi:app
      FLASK_DEBUG: "True"
      GUNICORN_BIND: "0.0.0.0:8000"
      PORT: 8000
      DATABASE_URI: "redis://redis:6379"
    networks:
      - dev
    depends_on:
      - redis

  redis:
    image: redis:6-alpine
    ports:
      - 6379
    volumes:
      - redis_data:/data
    networks:
      - dev

volumes:
  redis_data:

networks:
  dev:
